// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeN9BmXt1PRDKRUk4ZEJUbX_GPMg7zR-I',
    appId: '1:371726783381:web:d1cfc2d4d20dcb58511c9c',
    messagingSenderId: '371726783381',
    projectId: 'employeemanager-8c6f9',
    authDomain: 'employeemanager-8c6f9.firebaseapp.com',
    storageBucket: 'employeemanager-8c6f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rKzoLUmDiFmFx6t5ywFsi946IQDjYWk',
    appId: '1:371726783381:android:dd9e87aa00bedd6c511c9c',
    messagingSenderId: '371726783381',
    projectId: 'employeemanager-8c6f9',
    storageBucket: 'employeemanager-8c6f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8mHh-wpjX1gl5P5mErUlWiP-G-52EMM4',
    appId: '1:371726783381:ios:72d088af5e21f19c511c9c',
    messagingSenderId: '371726783381',
    projectId: 'employeemanager-8c6f9',
    storageBucket: 'employeemanager-8c6f9.appspot.com',
    iosBundleId: 'com.example.employeemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8mHh-wpjX1gl5P5mErUlWiP-G-52EMM4',
    appId: '1:371726783381:ios:5723f745662a7f7d511c9c',
    messagingSenderId: '371726783381',
    projectId: 'employeemanager-8c6f9',
    storageBucket: 'employeemanager-8c6f9.appspot.com',
    iosBundleId: 'com.example.employeemanager.RunnerTests',
  );
}
